### ISSUE TITLE
HTTP-Authentification

### ISSUE THREAD

**Issue by SimonOyen** [Capstoneris/CSS-Backend#7]
Authenticate user and set a cookie

**Comment by MarcusWichelmann** [comment]
I'm thinking of if we really want to use cookies here? There are multiple ways of doing authentication in such an SPA and all have some pros and cons. Cookie authentication, for example, is violating the statelessness of REST a bit and therefore introduces security vulnerabilities (CSRF, ..). I've gone this way in the past and it was a hassle to protect against these while still maintaining restfulness. :/
In the end it all boils down to what authentication system Capturis is going to use and because it's probably JWT, I think we should go either with JWT too, or do a very basic dummy-authentication system and just save a string in the local storage?

@Capstoneris/backend How hard is the implementation of JWT on your side? I'm sure there are some Java libraries? This would probably be the cleanest and easiest solution. Even easier than all this Cookie fun.

What do you think?

Great article, if you need some more background: https://medium.com/@jcbaey/authentication-in-spa-reactjs-and-vuejs-the-right-way-e4a9ac5cd9a3
